//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Orkidea.Deloitte.Approval.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApprovalRequest
    {
        public int id { get; set; }
        public System.DateTime dateRequest { get; set; }
        public string requestUser { get; set; }
        public int idDistributionList { get; set; }
        public string request { get; set; }
        public Nullable<bool> approved { get; set; }
        public Nullable<System.DateTime> dateApproval { get; set; }
        public string approvalUser { get; set; }
        public string comments { get; set; }
    
        public virtual DistributionList DistributionList { get; set; }
        public virtual WebUser WebUser { get; set; }
        public virtual WebUser WebUser1 { get; set; }
    }
}
